# Generated by Django 5.1 on 2026-07-09 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('upcoming', '临近'), ('overdue', '超期')], max_length=10, verbose_name='提醒类型')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '提醒记录',
                'verbose_name_plural': '提醒记录',
            },
        ),
    ]
