# Generated by Django 5.1 on 2026-07-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpwardNotifyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type_label', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('event_type', models.CharField(default='overdue', max_length=20)),
                ('sent_date', models.DateField()),
            ],
            options={
                'unique_together': {('content_type_label', 'object_id', 'event_type', 'sent_date')},
            },
        ),
    ]
