# Generated by Django 5.1 on 2026-07-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='wechat_dept_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='企业微信部门ID'),
        ),
    ]
