# Generated by Django 3.2.25 on 2026-09-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeComCorp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='用于 URL，如 default / b-corp，仅限字母数字和下划线连字符', max_length=32, unique=True, verbose_name='标识')),
                ('name', models.CharField(max_length=100, verbose_name='企业名称')),
                ('corp_id', models.CharField(max_length=100, verbose_name='企业ID (corp_id)')),
                ('agent_id', models.CharField(max_length=32, verbose_name='应用ID (agent_id)')),
                ('app_secret', models.CharField(max_length=200, verbose_name='应用密钥 (Secret)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_default', models.BooleanField(default=False, help_text='旧入口 /accounts/auto-login/ 落到的企业，全局只应有一条为真', verbose_name='默认企业')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '企业微信企业',
                'verbose_name_plural': '企业微信企业',
                'ordering': ['id'],
            },
        ),
    ]
