# Generated by Django 3.2.25 on 2026-09-15 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_seed_default_corp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wecom_corp',
            field=models.ForeignKey(blank=True, help_text='只有「主身份」写在这里，完整的多企业身份见「企业微信身份」', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.wecomcorp', verbose_name='所属企业'),
        ),
        migrations.CreateModel(
            name='WeComIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100, verbose_name='企业微信UserID')),
                ('is_primary', models.BooleanField(default=False, help_text='发企微消息时用哪套凭证。只有一个企业时无所谓，多企业时取主身份', verbose_name='主身份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='accounts.wecomcorp', verbose_name='企业')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_identities', to=settings.AUTH_USER_MODEL, verbose_name='账号')),
            ],
            options={
                'verbose_name': '企业微信身份',
                'verbose_name_plural': '企业微信身份',
                'ordering': ['user_id', '-is_primary', 'id'],
                'unique_together': {('user', 'corp'), ('corp', 'userid')},
            },
        ),
        migrations.CreateModel(
            name='WeComDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_dept_id', models.IntegerField(verbose_name='企业微信部门ID')),
                ('name', models.CharField(max_length=100, verbose_name='企微部门名称')),
                ('is_manual', models.BooleanField(default=False, help_text='勾选后自动同步不会覆盖本行的映射', verbose_name='人工指定')),
                ('is_root', models.BooleanField(default=False, help_text='企业自身那一层，不参与「主部门」解析', verbose_name='根部门')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depts', to='accounts.wecomcorp', verbose_name='企业')),
                ('department', models.ForeignKey(blank=True, help_text='留空表示该企微部门暂未对应到任何共享部门', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wecom_depts', to='accounts.department', verbose_name='映射到的共享部门')),
            ],
            options={
                'verbose_name': '企业微信部门映射',
                'verbose_name_plural': '企业微信部门映射',
                'ordering': ['corp_id', 'wechat_dept_id'],
                'unique_together': {('corp', 'wechat_dept_id')},
            },
        ),
    ]
