# Generated by Django 5.1 on 2026-07-09 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_userprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='阶段名称')),
                ('order', models.PositiveIntegerField(verbose_name='顺序号')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.department', verbose_name='负责部门')),
            ],
            options={
                'verbose_name': '阶段模板',
                'verbose_name_plural': '阶段模板',
                'ordering': ['order'],
                'unique_together': {('order',)},
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('stage_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='templates_app.stagetemplate', verbose_name='所属阶段模板')),
            ],
            options={
                'verbose_name': '子任务模板',
                'verbose_name_plural': '子任务模板',
                'ordering': ['order'],
            },
        ),
    ]
