# Generated by Django 5.1 on 2026-07-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetemplate',
            name='allow_parallel',
            field=models.BooleanField(default=False, verbose_name='允许并行（勾选后，该阶段无需等待上一阶段完成即可手动开始）'),
        ),
    ]
