# Generated by Django 5.1 on 2026-07-09 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_stagetemplate_allow_parallel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetemplate',
            name='default_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_stage_templates', to=settings.AUTH_USER_MODEL, verbose_name='默认负责人'),
        ),
    ]
