# Generated by Django 5.1 on 2026-07-11 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0003_stagetemplate_default_assignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='事项名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_item_templates', to='templates_app.tasktemplate', verbose_name='所属子任务模板')),
            ],
            options={
                'verbose_name': '最小事项模板',
                'verbose_name_plural': '最小事项模板',
                'ordering': ['order'],
            },
        ),
    ]
