# Generated by Django 5.1 on 2026-07-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0005_checklistitemtemplate_is_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='is_milestone',
            field=models.BooleanField(default=False, verbose_name='是否里程碑'),
        ),
    ]
