# Generated by Django 5.1 on 2026-07-09 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_products', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='product',
            name='expected_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计结束日期'),
        ),
        migrations.AddField(
            model_name='product',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='expected_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计结束日期'),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
