# Generated by Django 5.1 on 2026-07-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_actual_end_date_product_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstage',
            name='allow_parallel',
            field=models.BooleanField(default=False, verbose_name='允许并行'),
        ),
    ]
