# Generated by Django 5.1 on 2026-07-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productstage_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstage',
            name='expected_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计结束日期'),
        ),
        migrations.AlterField(
            model_name='productstage',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间'),
        ),
    ]
