# Generated by Django 5.1 on 2026-07-11 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='事项名称')),
                ('is_done', models.BooleanField(default=False, verbose_name='已完成')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='products.task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '最小事项',
                'verbose_name_plural': '最小事项',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskChecklistLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='日志内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='products.taskchecklistitem', verbose_name='所属事项')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '事项日志',
                'verbose_name_plural': '事项日志',
                'ordering': ['created_at'],
            },
        ),
    ]
