# Generated by Django 5.1 on 2026-07-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_taskchecklistitem_taskchecklistlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='所属类目'),
        ),
        migrations.AddField(
            model_name='product',
            name='demand_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='需求完成时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='demand_launch_date',
            field=models.DateField(blank=True, null=True, verbose_name='需求上市时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100, verbose_name='剂型'),
        ),
        migrations.AddField(
            model_name='product',
            name='efficacy',
            field=models.TextField(blank=True, verbose_name='功效描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='expected_gross_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='预期毛利率(%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_ingredients',
            field=models.TextField(blank=True, verbose_name='主要成分及含量'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_advantage',
            field=models.TextField(blank=True, verbose_name='原料优势'),
        ),
        migrations.AddField(
            model_name='product',
            name='platforms',
            field=models.CharField(blank=True, max_length=200, verbose_name='上架平台'),
        ),
        migrations.AddField(
            model_name='product',
            name='positioning',
            field=models.CharField(blank=True, max_length=200, verbose_name='产品定位'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='product',
            name='project_rationale',
            field=models.TextField(blank=True, verbose_name='立项依据'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_points',
            field=models.TextField(blank=True, verbose_name='核心卖点'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.CharField(blank=True, max_length=200, verbose_name='规格'),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='建议成本价'),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='建议零售价'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_audience',
            field=models.CharField(blank=True, max_length=200, verbose_name='目标人群'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_scenario',
            field=models.CharField(blank=True, max_length=200, verbose_name='场景应用'),
        ),
    ]
