# Generated by Django 5.1 on 2026-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchecklistitem',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='填写内容'),
        ),
    ]
