# Generated by Django 5.1 on 2026-07-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_checklist_item_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_milestone',
            field=models.BooleanField(default=False, verbose_name='是否里程碑'),
        ),
    ]
