# Generated by Django 3.2.25 on 2026-09-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_task_is_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('老品迭代', '老品迭代'), ('新品开发', '新品开发'), ('跨境自营', '跨境自营'), ('京东京造', '京东京造'), ('内地自营（含大贸）', '内地自营（含大贸）')], max_length=100, verbose_name='项目类型'),
        ),
    ]
