# Generated by Django 3.2.25 on 2026-09-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('老品迭代', '老品迭代'), ('新品开发', '新品开发')], max_length=100, verbose_name='项目类型'),
        ),
    ]
