# Generated by Django 3.2.25 on 2026-09-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='项目分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('老品迭代', '老品迭代'), ('新品开发', '新品开发')], max_length=100, verbose_name='项目类型'),
        ),
    ]
